### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by adambro** [rimesime/jest-matcher-http#56]
Thanks for this, looks exactly what I need. However I try to use it on TypeScript project and can't due to following error:
```
error TS2339: Property 'toReturnHttpCode' does not exist on type 'JestMatchers<number>'.
```
I guess the issue is missing TypeScript extension of standard JestMatchers type. Is TS on your agenda?

**Comment by rimesime** [comment]
Hi adambro!

I never worked with TypeScript, and it was therefore not on my agenda. But I'll look into it.

I reproduced the error you received, and managed to get a ts project's unit tests working by adding this file to jest-matcher-http/src:

```typescript
// file index.d.ts
declare namespace jest {
    interface Matchers<R> {
        toReturnHttpCode(status: number): CustomMatcherResult;
        toReturnHttpHeader(headerField: string, headerValue: string): CustomMatcherResult;
    }
}
```

But as I did not work with ts yet, I will have to look into the topic of integrating it into jest-matcher-http. If you have any resources on that or are willing to contribute, I would be happy to receive & support those efforts.

A small note on your error output there. As I am no expert on this, I might be wrong, but `JestMatchers<number>` looks to me as if you are calling e.g. `expect(200).toReturnHttpCode(200)`, you should instead do this: 

```javascript
const response = axios.get(...);
expect(response).toReturnHttpCode(200);
```

I hope that helps you already, and maybe you'll or I'll find time to incorporate this. Thanks for using this project :)

**Comment by adambro** [comment]
You're completely right that I was comparing HTTP status number, instead of the whole Response object. As you can see I'm new to TypeScript too :)

**Comment by rimesime** [comment]
Hey @adambro, I added support for typescript projects - do you maybe have time to have a look and check if that's working for you?
